api_p12_file = "../protected.p12"
console_url = "console.ves.volterra.io"
domain = "juice.gal.volcloud.net"
#end_timestamp = "1658260800"
namespace    = "arch"
shortname    = "juice"
#start_timestamp = "1658232000"
tenant       = "galileo"
